# Usa uma imagem base leve do Python
FROM python:3.10-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de dependências para o container
COPY requirements.txt .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código-fonte da aplicação para o container
COPY . .

# Expõe a porta 8080 para acesso à aplicação
EXPOSE 8080

# Comando para rodar a aplicação na porta 8080
CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8080"]
